### ISSUE TITLE
Playground crashes if XR is toggled off when the engine view is already toggled off

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#183]
Repro:
1. Run the Playground app
2. Tap Start XR
3. Tap Toggle EngineView
4. Tap Stop XR

One of two things will happen:
1. (Usually) Nothing seems to happen at first, but if you tap either Toggle EngineView or Stop XR (again), it will crash
2. (Sometimes) It will just hang and become unresponsive

**Comment by bghgary** [comment]
I have a partial fix for this with https://github.com/BabylonJS/BabylonNative/pull/746 which will address the hang that sometimes happens when toggling off the engine view while in XR.

This isn't necessarily the proper fix though. I haven't figured out why the code is continuing to render after the Android surface is destroyed. Ideally, XR should stop rendering completely when the window is set to null.

**Comment by bghgary** [comment]
The partial fix caused a regression #755. Need to make sure to check all XR scenarios for future fixes.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
