### ISSUE TITLE
How can the model scale freely like browser

### ISSUE THREAD

**Issue by fuyitaoqqq** [BabylonJS/BabylonReactNative#250]
Hey, i test BabylonJS with ArcRotateCamera in browser, it works well. And i just clone the BabylonReactNative repository and run the Playground demo.

My question is how i can scale or rotate the model freely like browser. In the demo application, i can just scale model by the slider. 

Or which doc can resolve my problem ?

i am not English native speaker, if there are bad manners in my words, forgive me plz.
Thanks a lot.

**Comment by ryantrem** [comment]
Hi @fuyitaoqqq - support for `ArcRotateCamera` (or rather the underlying input system) in Babylon Native is under way. See this forum thread for the latest discussion on this topic: https://forum.babylonjs.com/t/how-to-enable-touch-input-for-arcrotatecamera-on-babylon-react-native/13809/8

Closing this bug because it is not React Native specific and already tracked in the Babylon Native repo here: https://github.com/BabylonJS/BabylonNative/issues/605
