### ISSUE TITLE
Android precompiled package

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#29]
We should consider having a precompiled .so (and maybe loose java files for jni and talking to the RN API, including getting on the JS thread and getting the pointer to the JSCRuntime). This will make it much easier to consume the package since the consumer then will not need the NDK, CMake, or Ninja to be installed on their machine (and it will probably make the package smaller).

**Comment by CedricGuillemet** [comment]
I took a look at Android JSC and V8 NPM packages. Both work and are built the same way. Minor details for V8 are described at the end.

The NPM contains c/c++ headers and a maven package.
The maven package contains an .aar 
The .aar contains prebuilt binary .so for ABIs and prebuilt java classes.

.h and .a are not expected in .aar that's why they are in the npm.
A c/cpp program can link directly to a .so without .a. (With MSVC, you can generate a .lib from a .dll and link against)

It seems all symbols are exported from a .so. no dllexport-like needed (to be confirmed)
What can we do for Android packages?

- Add an Android integration project (basically the same I did some months ago)
    It works mostly like the Android Testapp with an .aar instead of an .apk
    the .aar will contain wrapper classes, babylon .js scripts and stripped BabylonNativeJNI.so for all ABIs
- On the CI, generate the maven package then
- create an include directory, copy the headers, move the maven package, generate and publish the .npm package
- optionally, publish the maven project to maven central

For the users, there are 2 ways to use the same binary produced.
For Java only users:
- add the maven central URL in gradle (gradle will download and install the package for you)
- java import the BabylonNative wrapper into the activity
- build, everything is imported from the .aar (resources, compiled java, .so). you are done. Ninja not needed here.

For ReactNative/C++ 
- add npm package in package.json
- npm install
- add includes and library path in your native CMakeLists
- link against BabylonNativeJNI.so (just like we did for v8 or jsc)
- add cmake command to copy BabylonNativeJNI.so in your jnilibs
- your build will not contain V8.so, jsc.so, resources,... if you need something more like resources .js, add the copy in cmake, just like you did just before.

It's also possible to add .h to the .aar but it doesn't seem to be a good practice.
V8 also provide in the npm package the unstripped versions of the .so. If you need them you have to manually replace the stripped version.
