### ISSUE TITLE
3D View not been rendered when using windows npm package

### ISSUE THREAD

**Issue by SergioRZMasson** [BabylonJS/BabylonReactNative#364]
## Overview

A user has reported on the forum that he was not able to get 3D view working when consuming Babylon React Native npm package for windows. At the time this was though as a versioning problem since @babylon/react-native-windows was using react-native-permissions@3.0.0 while all babylon react native packages were using version 2.1.0. Now that we have updated the package system and fixed this  react-native-permissions version issue we will need to investigate why this is happening. 

[Link to the forum issue](https://forum.babylonjs.com/t/babylonreactnative-no-3d-view-on-windows/28443)

## Steps to repro

- Create a new react native app targeting windows and install @babylonjs/react-native, and @babylonjs/react-native-windows
- Copy and paste the code from [App.tsx](https://github.com/SergioRZMasson/BabylonReactNative-GetStarted/blob/main/App.tsx)
- Application should compile and execute with no errors but 3D View should not be rendered

**Comment by ryantrem** [comment]
With classic RN debugging, it runs all the JS code remotely on the dev machine rather than on the device, which is incompatible with anything using JSI (it will slowly be deprecated as TurboModules and Fabric gain adoption). But in that case, we have code that detects classic debugging is enabled (which works on Android/iOS, but perhaps not Windows), and show an error. If this debug mode was enabled, and we didn't properly detect it, it's possible that we are silently failing somewhere due to a null JSI pointer or something like that.

**Comment by CedricGuillemet** [comment]
User was able to get it to run properly. Closing.
