### ISSUE TITLE
XRFrame should expose detected point cloud similar to how detected planes are exposed

### ISSUE THREAD

**Issue by hendryems** [BabylonJS/BabylonReactNative#52]
ARCore [documentation [link](https://developers.google.com/ar/discover/concepts#environmental_understanding)] exposes detecting of both planes and feature points.

However, XRFrame.worldInformation in BabylonJS only exposes detectedPlanes [Source [link](https://github.com/BabylonJS/Babylon.js/blob/7926f9a1b0e561344a734ef042284c5479a5240d/src/LibDeclarations/webxr.d.ts#L119)] but not feature points/point cloud.

This is a gap in the BabylonJS/BabylonReactNative feature set for apps looking to build a React Native app using BabylonReactNative as its XR abstraction.

**Comment by hendryems** [comment]
@jomcclan to verify @Alex-MSFT's in progress changes.

**Comment by Alex-MSFT** [comment]
This is now supported in BabylonReactNative for Android

**Comment by jomcclan** [comment]
The fix for iOS has gone into the Babylon Native repo.

Fix for iOS:https://github.com/BabylonJS/BabylonNative/pull/589
Fix for Android from August: https://github.com/BabylonJS/BabylonNative/pull/353/files

Leaving the issue open for the time being until the fix goes into the BabylonReactNative repo.

**Comment by bghgary** [comment]
@jomcclan Looks like this got merged into BabylonReactNative. Okay to close?

**Comment by jomcclan** [comment]
Closing now!
