### ISSUE TITLE
Shared project and C++Unit Tests

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonReactNative#587]
Does it make sense to move this folder/project:

https://github.com/BabylonJS/BabylonReactNative/tree/master/Modules/%40babylonjs/react-native/shared

to BabylonNative repo or a new repo? The goal is to be able to test it using C++ unittests. As it's an integration test, I think it can be done in BabylonNative Unittests.
ping @ryantrem @bghgary

**Comment by ryantrem** [comment]
This seems pretty react native specific. Can we introduce unit tests to this repo?

**Comment by CedricGuillemet** [comment]
We can but the issue is the frequency of updates. I'd like to know soon enough when a change is breaking BRN, without the need to kick a build in BRN.

**Comment by ryantrem** [comment]
We have another issue about leveraging DependaBot to create a BRN PR (and potentially PR/CI build) when the BN master branch is updated. Would it make sense to investigate that route?

**Comment by bghgary** [comment]
I think these are two different things. We want to be able to make changes to Babylon Native, build, test without having to know about dependencies. Ideally, we want to be able to test the scenarios that integrations (e.g. React Native) would do to integrate Babylon Native but without the integration code itself. I'm not sure bringing in this code module as a shared component makes sense since the dependency is backwards.

**Comment by CedricGuillemet** [comment]
BN CPP UnitTests tests will make sure integration will be fine with BRN. No need to share things between BN and BRN. Closing.
