### ISSUE TITLE
Some glbs don't render correctly on Android

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#61]
Making this issue title generic in case we find more of these... the model linked below renders correctly on iOS, but not on Android (tested with latest Babylon Native and Babylon.js (4.2.0-alpha.27)).

https://raw.githubusercontent.com/microsoft/experimental-pcf-control-assets/master/surface.glb

# Android
![surface.png](https://images.zenhubusercontent.com/5cddda05d341f7297326d49c/448e3074-01b7-4faa-a33b-41b6bd1011bd)

# iOS
![image.png](https://images.zenhubusercontent.com/5cddda05d341f7297326d49c/a68c0944-a6cc-4909-a8a2-99b8f7ddefb1)

**Comment by syntheticmagus** [comment]
The behavior of this seems telling, but I'm not quite sure of what. It's broken only on Android (both device and emulator, but in different ways) and the problem looks like a buffer misinterpretation problem, but that behavior isn't platform-specific, and no errors appear to be being thrown. This behavior might reveal more to someone with deeper knowledge of glTF than I have. With that in mind, if @Drigax has insights, we should run with those, but otherwise I think we should wait a week until @bghgary gets back and can take a look, then go from there.

**Comment by ryantrem** [comment]
This one is probably related: https://github.com/BabylonJS/BabylonReactNative/issues/70

**Comment by bghgary** [comment]
Fixed with #82
